spring.application.name=audio-transcribe
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.audio.transcription.base-url=https://api.groq.com/openai
spring.ai.openai.audio.transcription.api-key=${GROQ_API_KEY}
groq.api.key=${GROQ_API_KEY}
server.port=${PORT:8081}
